server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  JwtSecretKey: secretkey
  JwtIssuer: issuerforjwt
  JwtExpMin: 60
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: containers-us-west-143.railway.app
  PostgresqlPort: 7111
  PostgresqlUser: postgres
  PostgresqlPassword: LKjzozaMeoKoAETta0Kz
  PostgresqlDbname: railway
  PostgresqlSslMode: false
  PgDriver: pgx
